### ISSUE TITLE
Solving environment: failed

### ISSUE THREAD

**Issue by TheGermanEngie** [mirix/approaches-to-diarisation#3]
Hi -

I made an environment,yml file with the following configuration based off your dependencies requirements: 

name: diarize
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.8.17
  - scipy==1.10.1
  - plotly==5.15.0
  - pandas==1.5.3
  - numpy==1.22.4
  - pydub==0.25.1
  - sox
  - umap-learn==0.5.3
  - hdbscan
  - torch==2.0.1
  - stable-ts==2.6.4
  - scikit-learn==1.2.2
  - pip
  - pip:
    - git+https://github.com/facebookresearch/demucs.git@5d2ccf224f595b8654b0447e06f6adc866cca61a
    - git+https://github.com/NVIDIA/NeMo.git@c4e677a2d7aad47dbade8c3a0e47311a51d03bba

and typing conda env create -f environment.yml gives me this error:

Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - stable-ts==2.6.4
  - torch==2.0.1

This error message used to be longer but after I installed missing sox binaries most of them went away, so I know it's a dependency issue.

**Comment by mirix** [comment]
It would seem that those packages are not installable via Conda. Check the
respective GitHub sites and install them in the Conda environment via pip.
Alternatively, create an environment with venv and install everything via
pip. Also, you can renove the specific version numbers and just install the
latest releases.
